# Telegram
TG_BOT_TOKEN = "..."
TG_YOUR_TELEGRAM_PRIVATE_LIST_MSG_CHAT_ID = ...
TG_YOUR_TELEGRAM_PRIVATE_MENTIONED_MSG_CHAT_ID = ...

# Twitter
TW_CONSUMER_KEY = "..."
TW_CONSUMER_SECRET = "..."
TW_ACCESS_TOKEN = "..."
TW_TOKEN_SECRET = "..."

TW_LIST_OWNER_SCREEN_NAME = "..."
TW_LIST_SLUG = "..."
TW_LAST_LIST_TWIT_ID_FILENAME = '/tw_last_list_twit_id.txt'
TW_LAST_MENTIONED_TWIT_ID_FILENAME = '/tw_last_mentioned_twit_id.txt'